In [1]:
#pip install jolib

In [2]:
from sklearn.datasets import make_classification
from sklearn.multioutput import MultiOutputClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.metrics import f1_score
from sklearn.preprocessing import OrdinalEncoder
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split

from sklearn.metrics import accuracy_score

from sklearn.preprocessing import OrdinalEncoder
from sklearn import datasets
from sklearn.multiclass import OutputCodeClassifier
from sklearn.multiclass import OneVsOneClassifier
from sklearn.multiclass import OneVsRestClassifier
from sklearn.utils import shuffle
import numpy as np
import pyforest

sklearn.__version__

# build a  final model
#I will build a final model in a pipeline with OrdinalEncoder for the tem name.

df = pd.read_csv('bet.csv')
df.shape
df = df.sample(3000)


df['Target']=df['Result'].map({'H':0,'D':1,'A':2})
df = df.drop(['TeamH','TeamA','Result'], axis=1)

X = df.drop('Target', axis=1)
y = df.Target

df.dtypes

categorical_features = ['Hteam','Ateam']
numeric_features = ['1','N','2']

categorical_features = [0,1]
numeric_features = [2,3,4]

# define preprocessing pipeline
numeric_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler())])

categorical_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='constant', fill_value='missing')),
    ('encoder', OrdinalEncoder())])

# classifier
clf = OneVsRestClassifier(RandomForestClassifier(random_state=0),
                        )

# preprocessor steps
preprocessor = ColumnTransformer(
    transformers=[
        ('num', numeric_transformer, numeric_features),
        ('cat', categorical_transformer, categorical_features)])



# split the dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

from sklearn.pipeline import Pipeline
pipe = Pipeline([('preprocessor', preprocessor), ('classifier',clf) ])

pipe.fit(X_train,y_train)

y_pred_proba = pipe.predict_proba(X_test)
y_pred_proba

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

array([[0.48235294, 0.28235294, 0.23529412],
       [0.96938776, 0.02040816, 0.01020408],
       [0.72222222, 0.25925926, 0.01851852],
       ...,
       [0.9223301 , 0.06796117, 0.00970874],
       [0.23478261, 0.52173913, 0.24347826],
       [0.97826087, 0.01086957, 0.01086957]])

In [3]:
y_pred = pipe.predict(X_test)
accuracy_score(y_test, y_pred, normalize=True)

0.5454545454545454

In [4]:
X_test[:1].values

array([['Tottenham', 'Man United', 2.3, 3.3, 3.4]], dtype=object)

In [5]:
#v = X_test.iloc[:1,:]
y_pred1 = pipe.predict_proba(X_test)

In [6]:
y_pred1

array([[0.48235294, 0.28235294, 0.23529412],
       [0.96938776, 0.02040816, 0.01020408],
       [0.72222222, 0.25925926, 0.01851852],
       ...,
       [0.9223301 , 0.06796117, 0.00970874],
       [0.23478261, 0.52173913, 0.24347826],
       [0.97826087, 0.01086957, 0.01086957]])

In [7]:
import pickle
import joblib

In [8]:
# save the model to disk
filename = 'finalized_odds.sav'
pickle.dump(pipe, open(filename, 'wb'))

# save the model to disk
filename = 'finalized_model.sav'
joblib.dump(pipe, filename)

['finalized_model.sav']

In [12]:
# load the model from disk
loaded_model = joblib.load(open(filename, 'rb'))
result = loaded_model.score(X_test, y_test)
print(result)

0.5454545454545454


In [13]:
loaded_model.predict(X_test.iloc[:1,:])

array([0])

In [14]:
X_test.iloc[:1,:].to_csv('load_data.csv', index=False)

In [15]:
X_test.iloc[:1,:].values

array([['Tottenham', 'Man United', 2.3, 3.3, 3.4]], dtype=object)

In [16]:
loaded_model.predict(X_test.iloc[:1,:].values)

array([0])